// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // `prisma dev` serves the app database as `template1`, and Postgres copies
    // template1 into every newly created database — so the shadow database
    // Prisma creates for `migrate dev` inherits our schema and the init
    // migration fails with "type already exists". Pointing the shadow at an
    // existing database avoids that. Local development only; `migrate deploy`
    // on Vercel doesn't use a shadow database.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
